import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
my-application.c
""")

group = DefineGroup('my-application', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
