import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
my-application.c
rtumodbus.c
control_device.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
